### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by noraj** [giteshnxtlvl/cook-ingredients#1]
How to deploy this repository for cook ?

If cook is deployed under `/usr/share/cook` does having it deployed under `/usr/share/cook/cook-ingredients` will works or does it need to be under `/usr/share/cook` directly?

On cook repository there are references to this but it's not explain how to deploy it for cook to take it into account.

![image](https://user-images.githubusercontent.com/16578570/144714978-4471eedd-004f-4298-9a25-e185a3af12e0.png)

## update

I see here that at the first run of cook it will be downloaded and deployed under `$home/cook-ingredients` https://github.com/giteshnxtlvl/cook#-installation

I have to issues with that:

1. I doesn't do it, `$home/cook-ingredients` wasn't created on my system, **update** seems BA is using cook 1.6 and not 2.0 for now (see https://github.com/BlackArch/blackarch/issues/3278) the download of config file and conf file names were changed in 2.0
2. rather than `$home/cook-ingredients` it should be deployed under `~/.config/cook-ingredients` (`$XDG_CONFIG_HOME/cook-ingredients`) same as for https://github.com/giteshnxtlvl/cook/discussions/13#discussioncomment-684604

**Comment by glitchedgitz** [comment]
Actually, nuclei templates are also in $home directory, so I thought it might be good for users to find it right next to it if they want to modify it.

**Comment by glitchedgitz** [comment]
Also, the location for the config folder for windows is %appdata% and users have to dig too deep to modify it.
Chk here https://pkg.go.dev/os#UserConfigDir

**Comment by noraj** [comment]
> Actually, nuclei templates are also in $home directory, so I thought it might be good for users to find it right next to it if they want to modify it.

[XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) is a standard specification made by [freedesktop.org](https://en.wikipedia.org/wiki/Freedesktop.org) to unify base directory on Unix desktops and enhance interoperability.

nuclei may not implement the standard too.

> Also, the location for the config folder for windows is %appdata% and users have to dig too deep to modify it.

Yes go is following the XDG standard:

> On Unix systems, it returns $XDG_CONFIG_HOME as specified by https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html if non-empty, else $HOME/.config. On Darwin, it returns $HOME/Library/Application Support. On Windows, it returns %AppData%. On Plan 9, it returns $home/lib.

If any software would deploy a folder in our `$home` it would be very messy.

**Comment by glitchedgitz** [comment]
I know this, but I think it would be better to have it in $home in terms of user experience.
Even for every tool that needs high customization from the user-end, its config files should be easily accessible.
Also, users can change the directory if they want.
